version: '2'
services:

  grpcdeploymentservice:
    image: docker pull wilhelmstephan/grpc-api-for-saltstack-deployment-service
    ports:
       - "40011:40011"
    command: ["java","-jar","/fapra/gRPCContainer.jar","40011"]

  adapter:
    image: wilhelmstephan/grpc-to-graphql-adapter
    links:
      - grpcdeploymentservice:tssgrpcs32
    ports:
      - "40022:40022"
    environment:
      - API_HOST=tssgrpcs32
      - API_PORT=40011
      - API_PROTO_PATH=/api/main.proto
    volumes:
      - ./volumeWithProtoFile:/api
    depends_on:
      - grpcdeploymentservice
    command: ["node", "/fapra/graphQlServer.js", "40022"]

  adapterclient:
    build: ./ContainerAdapterClient/
    links:
      - adapter:tssgqs32
    environment:
      - GRAPHQL_SERVER_HOST=tssgqs32
      - GRAPHQL_SERVER_PORT=40022
      # PROVIDE YOUR INFORMATION:
      - FTP_USER=CHANGE
      - FTP_PW=CHANGE
      - FTP_HOST=CHANGE
      - FTP_PORT=CHANGE
      - FTP_PATH=CHANGE
      - KEY_PAIR_NAME=CHANGE
      - KEY_ID=CHANGE
      - KEY_SECRET=CHANGE
      - SECURITY_GROUP_NAME
    depends_on:
      - grpcdeploymentservice
      - adapter
    command: ["/fapra/graphQlClient.sh"]
